language: cpp 
compiler: gcc 

matrix:
  include:
    - os: linux
      env: COMPILER_NAME=gcc CXX=g++-9 CC=gcc-9
      addons:
        apt:
          packages:
            - g++-9
          sources: &sources
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test

env: 
  - OMP_NUM_THREADS=4 
 
before_script: 
  - mkdir build 
  - cd build 
  - cmake .. 
  - make 
  - make test 
 
script: make -j8
