dist: trusty
language: cpp 
compiler: gcc 
install: export CXX="g++-7"
matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
          apt:
            sources:
            - ubuntu-toolchain-r-test
            packages:
            - g++-7

env: 
  - OMP_NUM_THREADS=4 
 
before_script: 
  - mkdir build 
  - cd build 
  - cmake .. 
  - make 
  - make test 
 
script: make -j8
