branches:
  only:
  - master
  
image:
- Visual Studio 2017
 
before_build:
- cmd: |-
    mkdir build
    cd build
    cmake --version
    cmake .. -DCMAKE_BUILD_TYPE=Release

build:
  project: c:\projects\threadwatcher\build\ThreadWatcher.sln
  verbosity: minimal
  parallel: true

only_commits:
  files:
    - CMakeLists.txt
    - appveyor.yml
    - src/
    - test/
    - test/
    - cmake/